export default {
  task: {
    title: 'Inspection Tasks',
    desc: 'Configure scheduled inspection tasks. The service runs them automatically by Cron expression and generates reports.',
    newBtn: '+ New Task',
    table: {
      enabled: 'Enabled',
      name: 'Task Name',
      cron: 'Cron Expression',
      prompt: 'Task Prompt',
      lastRun: 'Last Run',
      nextRun: 'Next Run',
      actions: 'Actions',
      edit: 'Edit',
      runNow: 'Run Now',
      remove: 'Delete',
      empty: 'No inspection tasks yet. Click "+ New Task" in the top right.'
    },
    modal: {
      editTitle: 'Edit Inspection Task',
      createTitle: 'New Inspection Task',
      name: 'Task Name',
      namePlaceholder: 'e.g. Daily system inspection',
      cronExpr: 'Cron Expression',
      cronHint: 'Supports 5 fields (min hour day month week) or 6 fields (sec min hour day month week)',
      cronPlaceholder: 'Click "Configure" on the right to generate an expression',
      collapse: 'Collapse',
      expand: 'Configure',
      preview: 'Preview',
      nextRuns: 'Next execution times:',
      promptLabel: 'Task Prompt',
      promptPlaceholder: 'Describe what you want the inspection to analyze, e.g. check abnormal alerts, error logs and service health in the past 24 hours...',
      media: 'Notification Media',
      mediaHint: 'Reports are pushed automatically after generation; multiple selections allowed',
      mediaEmpty: 'No enabled notification media. Please create one in the "Notification Media" menu first.',
      dingtalk: 'DingTalk',
      enabledSwitch: 'Enable Task',
      cancel: 'Cancel',
      saving: 'Saving...',
      save: 'Save'
    },
    messages: {
      loadFailed: 'Failed to load tasks: ',
      nameRequired: 'Please enter a task name',
      cronRequired: 'Please enter a Cron expression',
      promptRequired: 'Please enter a task prompt',
      saveFailed: 'Failed to save: ',
      toggleFailed: 'Operation failed: ',
      runNowConfirm: 'Run inspection task "{name}" now? (Calling the LLM may take tens of seconds)',
      runSucceeded: 'Execution completed. Inspection report generated.',
      runFailed: 'Execution failed: ',
      deleteConfirm: 'Delete inspection task "{name}"?',
      deleteFailed: 'Failed to delete: '
    }
  },
  report: {
    title: 'Inspection Reports',
    desc: 'View historical reports generated by scheduled inspection tasks',
    filters: {
      task: 'Source Task',
      allTasks: 'All Tasks',
      status: 'Status',
      allStatus: 'All Status',
      query: 'Search',
      reset: 'Reset'
    },
    table: {
      score: 'Score',
      reportTitle: 'Report Title',
      task: 'Source Task',
      generatedAt: 'Generated At',
      summary: 'Summary',
      status: 'Status',
      actions: 'Actions',
      view: 'View',
      remove: 'Delete',
      emptyFiltered: 'No inspection reports match the current filters',
      empty: 'No inspection reports yet. Please configure an inspection task first.'
    },
    status: {
      completed: 'Completed',
      generating: 'Generating',
      failed: 'Failed'
    },
    messages: {
      loadFailed: 'Failed to load reports: ',
      deleteConfirm: 'Delete inspection report "{title}"?',
      deleteFailed: 'Failed to delete: '
    }
  },
  detail: {
    loading: 'Loading...',
    back: 'Back to List',
    overallScore: 'Overall Score',
    generateFailed: 'Generation Failed',
    loadFailed: 'Failed to load report: ',
    desc: 'Source: {task} · Generated: {date} · Overall score: {score}'
  },
  cron: {
    showSeconds: 'Show seconds field (6-part expression)',
    everyLabel: 'Every {label} ({wildcard})',
    interval: 'Every',
    range: 'Range',
    specific: 'Specify {unit}',
    multiple: '(multiple)',
    dayNote: 'After setting the day, the week field will be set to',
    weekNote: 'After setting the week, the day field will be set to',
    cancel: 'Cancel',
    confirm: 'OK',
    fields: {
      second: 'Second',
      minute: 'Minute',
      hour: 'Hour',
      day: 'Day',
      month: 'Month',
      week: 'Week'
    },
    units: {
      second: 'seconds',
      minute: 'minutes',
      hour: 'hours',
      day: 'days',
      month: 'months',
      week: 'weeks'
    },
    weekDays: {
      1: 'Monday',
      2: 'Tuesday',
      3: 'Wednesday',
      4: 'Thursday',
      5: 'Friday',
      6: 'Saturday',
      7: 'Sunday'
    },
    months: {
      1: 'Jan',
      2: 'Feb',
      3: 'Mar',
      4: 'Apr',
      5: 'May',
      6: 'Jun',
      7: 'Jul',
      8: 'Aug',
      9: 'Sep',
      10: 'Oct',
      11: 'Nov',
      12: 'Dec'
    },
    summary: {
      atMinute: 'at minute {m}',
      weekRange: 'Every {from}~{to}',
      weekList: 'Every {days}',
      weekSingle: 'Every {day}',
      monthDay: 'Monthly on day {d}',
      daily: 'Daily',
      atHour: '{h}:00',
      everyNHours: 'every {n} hours',
      daySeparator: ', '
    }
  }
}
